# Generated by Django 3.2.25 on 2026-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20260422_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesetting',
            options={'verbose_name': 'Store Setting', 'verbose_name_plural': 'Store Settings'},
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=79.0, max_digits=10),
        ),
    ]
