# Generated by Django 3.2.25 on 2026-04-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount cap', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max number of times this coupon can be used', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
